
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      storage_engine: innodb
      jdbc.time_zone: UTC
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        globally_quoted_identifiers: true #DB 예약어도 가능


#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

---



spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234
    hikari:
      maximum-pool-size: 2